import { Track } from '@/types/track';

export const data: Track[] = [
  {
    _id: 8,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    _id: 9,
    name: 'Salamander Ego',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Кантри'],
    duration_in_seconds: 105,
    album: 'Salamander Ego',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_Salamander_Ego.mp3',
    stared_user: [],
  },
  {
    _id: 10,
    name: 'Welcome to the Party',
    author: 'Cooper Cannell',
    release_date: '2020-02-11',
    genre: ['Рок'],
    duration_in_seconds: 95,
    release_date: '2019-03-12',
    genre: ['Кантри'],
    duration_in_seconds: 234,
    album: 'Welcome to the Party',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Cooper_Cannell_-_Welcome_to_the_Party.mp3',
    stared_user: [],
  },
  {
    _id: 11,
    name: 'Fluffing a Duck',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 208,
    release_date: '2011-06-12',
    genre: ['Электроника'],
    duration_in_seconds: 103,
    album: 'Fluffing a Duck',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_Fluffing_a_Duck.mp3',
    stared_user: [],
  },
  {
    _id: 12,
    name: 'Rockstar',
    author: 'Audionautix',
    release_date: '2020-02-11',
    genre: ['Рок'],
    duration_in_seconds: 165,
    release_date: '2015-06-12',
    genre: ['Рок'],
    duration_in_seconds: 165,
    album: 'Rockstar',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Audionautix_-_Rockstar.mp3',
    stared_user: [],
  },
  {
    _id: 13,
    name: 'Enthusiast',
    author: 'Tours',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 123,
    release_date: '2015-06-12',
    genre: ['Электроника'],
    duration_in_seconds: 185,
    album: 'Enthusiast',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Tours_-_Enthusiast.mp3',
    stared_user: [],
  },
  {
    _id: 14,
    name: 'UFO',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 164,
    album: 'UFO',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_UFO.mp3',
    name: 'Shipping Lanes',
    author: 'Chad Crouch',
    release_date: '2015-06-12',
    genre: ['Кантри'],
    duration_in_seconds: 126,
    album: 'Shipping Lanes',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_UFO.mp3',
    stared_user: [],
  },
  {
    _id: 15,
    name: 'Islamander Light',
    author: 'Moombahton',
    release_date: '2020-02-11',
    genre: ['Электронная музыка'],
    duration_in_seconds: 156,
    album: 'Islamander Light',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Moombahton_-_Islamander_Light.mp3',
    name: 'PFM',
    author: 'Ilya Truhanov',
    release_date: '2017-05-18',
    genre: ['Инди'],
    duration_in_seconds: 163,
    album: 'PFM',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Moombahton_-_Islamander_Light.mp3',
    stared_user: [],
  },
  {
    _id: 16,
    name: 'Midnight Tale',
    author: 'Freedom Trail Studio',
    release_date: '2020-02-11',
    genre: ['Классическая музыка'],
    duration_in_seconds: 187,
    release_date: '2018-03-24',
    genre: ['Кантри'],
    duration_in_seconds: 227,
    album: 'Midnight Tale',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Freedom_Trail_Studio_-_Midnight_Tale.mp3',
    stared_user: [],
  },
  {
    _id: 17,
    name: 'Chale',
    author: 'Alexander Nesterenko',
    release_date: '2020-02-11',
    genre: ['Рок'],
    duration_in_seconds: 145,
    album: 'Chale',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nesterenko_-_Chale.mp3',
    name: 'Signature',
    author: 'Jeremy Blake',
    release_date: '2017-06-09',
    genre: ['Электроника'],
    duration_in_seconds: 179,
    album: 'Signature',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Alexander_Nesterenko_-_Chale.mp3',
    stared_user: [],
  },
  {
    _id: 18,
    name: 'The Longest Year',
    author: 'Kevin MacLeod',
    release_date: '2020-02-11',
    genre: ['Кантри'],
    duration_in_seconds: 178,
    album: 'The Longest Year',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_The_Longest_Year.mp3',
    name: 'Brave',
    author: 'Aakash Gandhi',
    release_date: '2019-03-18',
    genre: ['Рок'],
    duration_in_seconds: 192,
    album: 'Brave',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Kevin_MacLeod_-_The_Longest_Year.mp3',
    stared_user: [],
  },
  {
    _id: 19,
    name: 'Summer',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 134,
    album: 'Summer',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Summer.mp3',
    name: 'Dreams',
    author: 'Aakash Gandhi',
    release_date: '2019-03-18',
    genre: ['Рок'],
    duration_in_seconds: 234,
    album: 'Dreams',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Summer.mp3',
    stared_user: [],
  },
  {
    _id: 20,
    name: 'Sunshine',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 167,
    album: 'Sunshine',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Sunshine.mp3',
    name: 'Me & You',
    author: 'Gravity Sound',
    release_date: '2020-02-14',
    genre: ['Поп'],
    duration_in_seconds: 167,
    album: 'Sunshine',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Sunshine.mp3',
    stared_user: [],
  },
  {
    _id: 21,
    name: 'Winter',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 189,
    album: 'Winter',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Winter.mp3',
    name: 'Soul',
    author: 'Gravity Sound',
    release_date: '2020-04-27',
    genre: ['Поп'],
    duration_in_seconds: 189,
    album: 'Winter',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Winter.mp3',
    stared_user: [],
  },
  {
    _id: 22,
    name: 'Spring',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 156,
    album: 'Spring',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Spring.mp3',
    name: 'World',
    author: 'Gravity Sound',
    release_date: '2020-07-06',
    genre: ['Поп'],
    duration_in_seconds: 156,
    album: 'Spring',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Spring.mp3',
    stared_user: [],
  },
  {
    _id: 23,
    name: 'Autumn',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 172,
    album: 'Autumn',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Autumn.mp3',
    name: 'Time',
    author: 'Gravity Sound',
    release_date: '2020-11-15',
    genre: ['Поп'],
    duration_in_seconds: 172,
    album: 'Autumn',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Autumn.mp3',
    stared_user: [],
  },
  {
    _id: 24,
    name: 'Rain',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 148,
    album: 'Rain',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Rain.mp3',
    name: 'Puppy',
    author: 'Gravity Sound',
    release_date: '2021-02-05',
    genre: ['Поп'],
    duration_in_seconds: 148,
    album: 'Rain',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Rain.mp3',
    stared_user: [],
  },
  {
    _id: 25,
    name: 'Snow',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 163,
    album: 'Snow',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Snow.mp3',
    name: 'Puppy2',
    author: 'Gravity Sound',
    release_date: '2021-03-17',
    genre: ['Поп'],
    duration_in_seconds: 163,
    album: 'Snow',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Snow.mp3',
    stared_user: [],
  },
  {
    _id: 26,
    name: 'Wind',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 151,
    album: 'Wind',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Wind.mp3',
    name: 'Puppy3',
    author: 'Gravity Sound',
    release_date: '2021-05-14',
    genre: ['Поп'],
    duration_in_seconds: 151,
    album: 'Wind',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Wind.mp3',
    stared_user: [],
  },
  {
    _id: 27,
    name: 'Fire',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 175,
    album: 'Fire',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Fire.mp3',
    name: 'Puppy4',
    author: 'Gravity Sound',
    release_date: '2021-07-16',
    genre: ['Поп'],
    duration_in_seconds: 175,
    album: 'Fire',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Fire.mp3',
    stared_user: [],
  },
  {
    _id: 28,
    name: 'Earth',
    author: 'Benjamin Tissot',
    release_date: '2020-02-11',
    genre: ['Поп'],
    duration_in_seconds: 142,
    album: 'Earth',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Earth.mp3',
    name: 'Puppy5',
    author: 'Gravity Sound',
    release_date: '2021-08-24',
    genre: ['Поп'],
    duration_in_seconds: 142,
    album: 'Earth',
    logo: null,
    track_file:
      'https://webdev-music-003b5b991590.herokuapp.com/media/music_files/Benjamin_Tissot_-_Earth.mp3',
    stared_user: [],
  },
];
